proxies:
# Config XL Akrab #
# Main Servers
  # Quota Based
  - name: SG HE
    server: sg1-trojan.bonds.id
    port: 443
    type: trojan
    password: 37e90730-0da0-11ed-b28e-1239d0255272
    skip-cert-verify: true
    sni: gz0.googleusercontent.com
    udp: true
    
  - name: SG OVH
    server: 1d481760-0da0-11ed-b596-1239d0255272
    port: 443
    type: trojan
    password: 3b9aa3d0-ff0e-11ec-bb52-1239d0255272
    skip-cert-verify: true
    sni: gz0.googleusercontent.com
    udp: true

  - name: TH CAT
    server: th1-trojan.bonds.id
    port: 443
    type: trojan
    password: 5f461f20-0da0-11ed-8f60-1239d0255272
    skip-cert-verify: true
    sni: gz0.googleusercontent.com
    udp: true
  
  # Weekly
  - name: ID Biznet - 03.08
    server: id-lb.sshkit.org
    port: 443
    type: vmess
    uuid: 6fea1649-425b-4092-bf53-29792152c925
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: gz0.googleusercontent.com
    network: ws
    ws-opts:
      path: /sshkit/iekas/62e123783c91c/
      headers:
        Host: gz0.googleusercontent.com
    udp: true

  - name: ID APIK - 31.07
    server: id.vmes.xyz
    port: 443
    type: vmess
    uuid: f36d7764-4913-4158-be1c-3965d479edaf
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: gz0.googleusercontent.com
    network: ws
    ws-opts:
      path: /JAGOANSSH/
      headers:
        Host: gz0.googleusercontent.com
    udp: true
    
  - name: SG AMP - 03.08
    server: sg-atha.v2-ray.com
    port: 443
    type: vmess
    uuid: 16ceca7e-d27b-4b0d-acd7-a1d70e278be8
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: gz0.googleusercontent.com
    network: ws
    ws-opts:
      path: /fastssh/laksde/62e123627a215/
      headers:
        Host: gz0.googleusercontent.com
    udp: true

  - name: SG LINODE - 31.07 
    server: sgv-1.openv2ray.com
    port: 443
    type: vmess
    uuid: a40d34c6-b77c-4648-9210-3e8d2f4226b5
    alterId: 16
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: gz0.googleusercontent.com
    network: ws
    ws-opts:
      path: /u/opentunnel.net-gddhxs
      headers:
        Host: gz0.googleusercontent.com
    udp: true

# Load Balance SG
  - name: HE 1
    server: sg1-trojan.bonds.id
    port: 443
    type: trojan
    password: 0fe219d0-0d9f-11ed-9622-1239d0255272
    skip-cert-verify: true
    sni: gz0.googleusercontent.com
    udp: true
        
  - name: HE 2
    server: sg2-trojan.bonds.id
    port: 443
    type: trojan
    password: 80682960-0d9f-11ed-87c2-1239d0255272
    skip-cert-verify: true
    sni: gz0.googleusercontent.com
    udp: true

# Load Balance ID
  - name: Biznet 1
    server: id2-trojan.bonds.id
    port: 443
    type: trojan
    password: a81e6370-0d9f-11ed-8239-1239d0255272
    skip-cert-verify: true
    sni: gz0.googleusercontent.com
    udp: true
    
  - name: Biznet 2
    server: id5-trojan.bonds.id
    port: 443
    type: trojan
    password: b8689e30-0d9f-11ed-9137-1239d0255272
    skip-cert-verify: true
    sni: gz0.googleusercontent.com
    udp: true

proxy-groups:
  - name: Servers
    type: select
    proxies:
      - Main Servers
      - SG LB Servers
      - ID LB Servers

  - name: Main Servers
    type: select
    proxies:
      - SG HE
      - SG OVH
      - TH CAT
      - ID Biznet - 03.08
      - ID APIK - 31.07
      - SG AMP - 03.08
      - SG LINODE - 31.07 
    url: http://www.gstatic.com/generate_204
    interval: 300

  - name: SG LB Servers
    type: load-balance
    proxies:
      - HE 1
      - HE 2
    strategy: consistent-hashing
    disable-udp: false
    url: http://www.gstatic.com/generate_204
    interval: 300

  - name: ID LB Servers
    type: load-balance
    proxies:
      - Biznet 1 
      - Biznet 2
    strategy: consistent-hashing
    disable-udp: false
    url: http://www.gstatic.com/generate_204
    interval: 300

rules:
  - MATCH,Servers
