proxies:
# Config XL
proxy-groups:
  - name: Servers
    type: select
    proxies:
      - Main Server
      - Load Balance
      - Best Ping
      - Fallback
  - name: Main Server
    type: select
    url: http://hi.bonds.id/ping
    interval: 300
    use:
      - "1. Main Server"
  - name: Load Balance
    type: load-balance
    strategy: consistent-hashing
    url: http://hi.bonds.id/ping
    interval: 300
    use:
      - "2. Group Server"
  - name: Best Ping
    type: url-test
    url: http://hi.bonds.id/ping
    interval: 300
    tolerance: 200
    use:
      - "2. Group Server"
  - name: Fallback
    type: fallback
    url: http://hi.bonds.id/ping
    interval: 300
    use:
      - "2. Group Server"
proxy-providers:
  "1. Main Server":
    type: http
    url: "https://raw.githubusercontent.com/arijatipermana/VPN/main/proxy_provider/main_server.yaml"
    interval: 3600
    path: ./proxy_provider/main_server.yaml
    health-check:
      enable: true
      url: http://hi.bonds.id/ping
      interval: 300
  "2. Group Server":
    type: http
    url: "https://raw.githubusercontent.com/arijatipermana/VPN/main/proxy_provider/group_server.yaml"
    interval: 3600
    path: ./proxy_provider/group_server.yaml
    health-check:
      enable: true
      url: http://hi.bonds.id/ping
      interval: 300
rules:
  - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
  - IP-CIDR6,::1/128,REJECT,no-resolve
  - MATCH,Servers
